#!/bin/tcsh

#----$1 is the unaugmented ratings.csv file
foreach line (`cat $1`)
# echo "Processing $line"
    while (`echo $line | grep -c "^[A-Z][A-Z][A-Z][0-9][0-9][0-9].*[0-9]\.[0-9][0-9],,"`)
        set line = `echo $line | sed -e "s/\([0-9]\.[0-9][0-9]\),,/\1,\1,/"`
# echo "Now it is  $line"
    end
    echo $line
end
