#!/bin/tcsh

echo -n "Problem,SZS,"
foreach dir (`ls -d TPTP* | sort -r`)
    set release=`basename $dir -Documents | sed -e "s/TPTP-//"`
    echo -n "$release,"
end
echo ""
exit
foreach problem (`cat AllProblemNames`)
    set output=`grep -m1 "$problem" AllProblemSZS | sed -e "s/ /,/"`
    echo -n "${output},"
    foreach dir (`ls -d TPTP* | sort -r`)
        set output=`grep -m1 "$problem" $dir/*SolutionsSummary.txt | sed -e "s/.* //"`
        echo -n "${output},"
    end
    echo ""
end
