#!/bin/tcsh

#----$1 is the augmented ratings.csv file
foreach line (`cat $1`)
# echo "Processing $line"
    if (`echo $line | grep -c "^[A-Z][A-Z][A-Z][0-9][0-9][0-9]"`) then
# echo "$line"
        set line_parts = ($line:as/,/ /)
        echo -n "$line_parts[1],$line_parts[2],"
        set output = "$line_parts[$#line_parts]"
        set current = "$line_parts[$#line_parts]"
        foreach index (`seq $#line_parts 4`)
            @ next = $index - 1
            if (`echo "$line_parts[$next] < $current" | bc`) then
# echo "Need to replace $line_parts[$next] with $line_parts[$index]"
                set current = "$line_parts[$next]"
            endif
            set output = "$current,$output"
        end
        echo "$output"
    endif
end
